# Generated by Django 5.2.1 on 2025-05-13 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('garages', '__first__'),
        ('mechanics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='garage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garages.garage'),
        ),
        migrations.AddField(
            model_name='booking',
            name='mechanic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mechanics.mechanic'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='mechanic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='mechanics.mechanic'),
        ),
        migrations.AddField(
            model_name='booking',
            name='time_slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookings.timeslot'),
        ),
    ]
