# Generated by Django 5.2.1 on 2025-05-14 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import datetime



class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        ('garages', '__first__'),
        ('mechanics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='mechanic',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time_slot',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='service_type',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='garage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='garages.garage'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='mechanics.mechanic'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('garage__isnull', True), ('mechanic__isnull', False)), models.Q(('garage__isnull', False), ('mechanic__isnull', True)), _connector='OR'), name='mechanic_or_garage'),
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
